---
rails_na_frontend:
  /home/rails/mysageone_us/current/log/:
    - '*.log'
  /home/rails/sageone_us/current/log/:
    - '*.log'
  /var/log:
    - messages
    - cron
    - maillog
    - yum
    - secure
  /var/log/httpd:
    - access
    - error
    - ssl
rails_ca_frontend:
  /home/rails/mysageone_ca/current/log/:
    - '*.log'
  /home/rails/sageone_ca/current/log/:
    - '*.log'
  /var/log:
    - messages
    - cron
    - maillog
    - yum
    - secure
  /var/log/httpd:
    - access
    - error
    - ssl
